# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-17 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('0', 'shoes'), ('1', 'jeans'), ('2', 'shirt'), ('3', 'purse')], max_length=30, null=True)),
                ('sub_category', models.CharField(max_length=30, null=True)),
                ('company', models.TextField(blank=True, max_length=500, verbose_name='Com')),
                ('image', models.ImageField(blank=True, upload_to='/images')),
                ('price', models.CharField(max_length=500, verbose_name='price')),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
