# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-17 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171017_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(default=10, max_length=30),
        ),
    ]
