# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180110_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(b'0', b'T-shirts'), (b'1', b'Shirts'), (b'2', b'Blazers'), (b'3', b'Kurtas'), (b'4', b'Jeans'), (b'5', b'Trousers'), (b'6', b'Shorts'), (b'7', b'Hoodies'), (b'8', b'Jackets'), (b'9', b'Sweaters'), (b'10', b'Men shoes'), (b'11', b'Kurtas'), (b'12', b'Salwar suits'), (b'13', b'Sarees'), (b'14', b'Tops'), (b'15', b'Jeans'), (b'16', b'Coats and Jackets'), (b'17', b'Women Hoddies'), (b'18', b'Cardigans'), (b'23', b'Women Shoes'), (b'19', b'Kids Jackets'), (b'20', b'Girls dresses'), (b'21', b'Boys dresses'), (b'22', b'Kids sweatshirts')], max_length=30, null=True),
        ),
    ]
