# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/parrot.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
